apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-sync
  labels:
    app: group-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-sync
  template:
    metadata:
      labels:
        app: group-sync
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9002"
    spec:
      containers:
        - name: group-sync
          image: group-sync
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9002
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: BPL_DEBUG_ENABLED
              value: "true"
            - name: BPL_DEBUG_PORT
              value: "8001"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9002
            initialDelaySeconds: 10
            periodSeconds: 5
            terminationGracePeriodSeconds: 150
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9002
            initialDelaySeconds: 10
            periodSeconds: 5
            terminationGracePeriodSeconds: 150