apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-sync
  labels:
    app: group-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-sync
  template:
    metadata:
      labels:
        app: group-sync
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9002"
    spec:
      containers:
        - name: group-sync
          image: group-sync
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9002
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-1.26.0.jar
            - name: OTEL_SERVICE_NAME
              value: group-service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://tempo
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: BPL_DEBUG_ENABLED
              value: "true"
            - name: BPL_DEBUG_PORT
              value: "8001"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9002
            initialDelaySeconds: 10
            periodSeconds: 5
            terminationGracePeriodSeconds: 150
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9002
            initialDelaySeconds: 10
            periodSeconds: 5
            terminationGracePeriodSeconds: 150
          volumeMounts:
            - name: group-sync-config-volume
              mountPath: /workspace/config
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: group-sync-config-volume
          configMap:
            name: group-sync-config