server:
  error:
    include-stacktrace: never
spring:
  rabbitmq:
    host: grouphq-rabbitmq
grouphq:
  features:
    groups:
      create: false
      status: false
      join: true
      leave: true
  group-service:
    url: http://group-service
    get-groups-timeout-milliseconds: 3000
    get-groups-retry-attempts: 3
    get-groups-retry-backoff-milliseconds: 100
    get-group-members-timeout-milliseconds: 3000
    get-group-members-retry-attempts: 3
    get-group-members-retry-backoff-milliseconds: 100